import type { NextPage } from 'next';
import Head from 'next/head';
import Login from './login';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Weeding</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Login />
    </main>
  </div>
);

export default Home;
