import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Login from './login';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Weeding</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <Login />
    </main>
  </div>
);

export default Home;
